services:
  - type: web
    name: bitcoin-monitor
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    healthCheckPath: /
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    envVars:
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
